# Generated by Django 4.2.7 on 2023-11-03 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UrlSchema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("url_code", models.CharField(max_length=100)),
                ("long_url", models.CharField(max_length=100)),
                ("short_url", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
